let levels = [{
      "globalMoney": 8000,
      "money": 1250,
      "nbr": 5,
      "life": 100,
      "detect": 200,
      "range": 0,
      "damage": 5,
      "attackDelay": 0.2,
      "callForHelp": true,
      "canCharge": false,
      "explosion": false,
      "zombie": false
    },
    {
      "globalMoney": 16000,
      "money": 2000,
      "nbr": 15,
      "life": 150,
      "detect": 100,
      "range": 0,
      "damage": 10,
      "attackDelay": 0.5,
      "callForHelp": true,
      "canCharge": false,
      "explosion": false,
      "zombie": false},
    {
      "globalMoney": 15000,
      "money": 2500,
      "nbr": 30,
      "life": 200,
      "detect": 75,
      "range": 0,
      "damage": 10,
      "attackDelay": 0.5,
      "callForHelp": true,
      "canCharge": false,
      "explosion": false,
      "zombie": false},
    {
      "globalMoney": 30000,
      "money": 3000,
      "nbr": 50,
      "life": 100,
      "detect": 200,
      "range": 0,
      "damage": 10,
      "attackDelay": 0.2,
      "callForHelp": true,
      "canCharge": false,
      "explosion": false,
      "zombie": false},
    {
      "globalMoney": 150000,
      "money": 4000,
      "nbr": 1,
      "life": 10000,
      "detect": 500,
      "range": 100,
      "damage": 100,
      "attackDelay": 5,
      "callForHelp": true,
      "canCharge": true,
      "explosion": false,
      "zombie": false},
    {
      "globalMoney": 350000,
      "money": 5000,
      "nbr": 500,
      "life": 100,
      "detect": 200,
      "range": 0,
      "damage": 10,
      "attackDelay": 0.4,
      "callForHelp": true,
      "canCharge": false,
      "explosion": false,
      "zombie": false}
  ];
