let levels = [{
      "globalMoney": 10000,
      "money": 3000,
      "nbr": 5,
      "life": 100,
      "detect": 200,
      "range": 0,
      "damage": 5,
      "attackDelay": 0.2,
      "callForHelp": true,
      "canCharge": false,
      "explosion": false,
      "zombie": false
    },
    {
      "globalMoney": 26000,
      "money": 3500,
      "nbr": 15,
      "life": 150,
      "detect": 100,
      "range": 0,
      "damage": 10,
      "attackDelay": 0.5,
      "callForHelp": true,
      "canCharge": false,
      "explosion": false,
      "zombie": false},
    {
      "globalMoney": 35000,
      "money": 4000,
      "nbr": 30,
      "life": 200,
      "detect": 75,
      "range": 0,
      "damage": 10,
      "attackDelay": 0.5,
      "callForHelp": true,
      "canCharge": false,
      "explosion": false,
      "zombie": false},
    {
      "globalMoney": 50000,
      "money": 5000,
      "nbr": 50,
      "life": 100,
      "detect": 200,
      "range": 0,
      "damage": 10,
      "attackDelay": 0.2,
      "callForHelp": true,
      "canCharge": false,
      "explosion": false,
      "zombie": false},
    {
      "globalMoney": 250000,
      "money": 6000,
      "nbr": 1,
      "life": 10000,
      "detect": 500,
      "range": 100,
      "damage": 100,
      "attackDelay": 5,
      "callForHelp": true,
      "canCharge": true,
      "explosion": false,
      "zombie": false},
    {
      "globalMoney": 350000,
      "money": 70000,
      "nbr": 500,
      "life": 100,
      "detect": 200,
      "range": 0,
      "damage": 10,
      "attackDelay": 0.4,
      "callForHelp": true,
      "canCharge": false,
      "explosion": false,
      "zombie": false}
  ];
